services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sigep2-client-dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    stdin_open: true
    tty: true